name: zero-hero-environment
version: 1.0.0
summary: Azure Zero to Hero Environment
description:  Step by step Azure VM ARM template.
runner: xayoacr.azurecr.io/ade:latest
templatePath: azuredeploy.json
parameters:
  - id: Template Type
    name: Type of template to be deployed 
    description: Choose of the the demplete types to be deployed 
    type: string
    required: true
    allowed:
      - "python"
      - "nodejs"
      - "java"
