name: windows-vm-environment
version: 1.0.0
summary: Azure Windows 11 VM Environment
description:  Deploys a Windows 11 VM with Visual Studio using ARM template.
runner: ARM
templatePath: azuredeploy.json
parameters:
  - id: adminPassword
    name: Admin Password
    description: The password for the Windows VM administrator account.
    type: string
    required: true
    secret: true
