name: windows-vm-environment
description: Deploys a Windows 11 VM with Visual Studio using ARM template.
resource:
  templatePath: azuredeploy.json
parameters:
  - id: adminPassword
    displayName: Admin Password
    description: The password for the Windows VM administrator account.
    type: string
    required: true
    secret: true
